### ISSUE TITLE
topoplot channel exclusion

### ISSUE THREAD

**Issue by rb643** [janfreyberg/ssvepy#5]
Perhaps more an improvement if the topoplot function could include a channel inclusion argument. For Biosemi at the moment it signal that the external electrodes have overlapping position and thus won't plot anything:

ssvep0[0].topoplot_snr()

ValueError: The following electrodes have overlapping positions, which causes problems during visualization:
EXG1, EXG2, EXG3, EXG4, EXG5, EXG6, EXG7, EXG8, STI 014

**Comment by janfreyberg** [comment]
Ah interesting! Yes, that's a good idea.

**Comment by janfreyberg** [comment]
@rb643 I don't think I could ever reproduce this but I think that's because I was maybe using a more up-to-date version of this?

This works for me:

```python
import mne
import ssvepy
from pathlib import Path

file = Path('debug/EG-CTR-0115-Face-Categorisation.bdf')

raw = mne.io.read_raw_edf(
    file, montage=mne.channels.read_montage('biosemi64'),
    eog=[f'EXG{n}' for n in range(1, 9)]
)
raw.info['subject_info'] = {
    'pid': file.name[7:11],
    'group': file.name[3:6]
}

events = mne.find_events(raw)
events = events[events[:, 2] < 255, :]

epochs = mne.Epochs(
    raw, events,
    tmin=0, tmax=4, preload=True
).set_eeg_reference().load_data().apply_proj()

ssvep = ssvepy.Ssvep(epochs, [1.2, 6], compute_tfr=False)

ssvep.topoplot_snr()
```

**Comment by janfreyberg** [comment]
I just released a new version, so maybe try and install from there!

**Comment by rb643** [comment]
Fixed :)
